//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoNido.wcfNido {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfNido")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsLogin", Namespace="http://schemas.datacontract.org/2004/07/clsEntidades")]
    [System.SerializableAttribute()]
    public partial class clsLogin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExitoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Id_PermisoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Id_RolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string claveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exito {
            get {
                return this.ExitoField;
            }
            set {
                if ((this.ExitoField.Equals(value) != true)) {
                    this.ExitoField = value;
                    this.RaisePropertyChanged("Exito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id_Permiso {
            get {
                return this.Id_PermisoField;
            }
            set {
                if ((this.Id_PermisoField.Equals(value) != true)) {
                    this.Id_PermisoField = value;
                    this.RaisePropertyChanged("Id_Permiso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id_Rol {
            get {
                return this.Id_RolField;
            }
            set {
                if ((this.Id_RolField.Equals(value) != true)) {
                    this.Id_RolField = value;
                    this.RaisePropertyChanged("Id_Rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Usuario {
            get {
                return this.Id_UsuarioField;
            }
            set {
                if ((this.Id_UsuarioField.Equals(value) != true)) {
                    this.Id_UsuarioField = value;
                    this.RaisePropertyChanged("Id_Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clave {
            get {
                return this.claveField;
            }
            set {
                if ((object.ReferenceEquals(this.claveField, value) != true)) {
                    this.claveField = value;
                    this.RaisePropertyChanged("clave");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsUsuario", Namespace="http://schemas.datacontract.org/2004/07/clsEntidades")]
    [System.SerializableAttribute()]
    public partial class clsUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BloqueadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaBloqueoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntentosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UltimoIntentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UltimoLoginExitosoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Bloqueado {
            get {
                return this.BloqueadoField;
            }
            set {
                if ((this.BloqueadoField.Equals(value) != true)) {
                    this.BloqueadoField = value;
                    this.RaisePropertyChanged("Bloqueado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni {
            get {
                return this.DniField;
            }
            set {
                if ((object.ReferenceEquals(this.DniField, value) != true)) {
                    this.DniField = value;
                    this.RaisePropertyChanged("Dni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaBloqueo {
            get {
                return this.FechaBloqueoField;
            }
            set {
                if ((this.FechaBloqueoField.Equals(value) != true)) {
                    this.FechaBloqueoField = value;
                    this.RaisePropertyChanged("FechaBloqueo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Intentos {
            get {
                return this.IntentosField;
            }
            set {
                if ((this.IntentosField.Equals(value) != true)) {
                    this.IntentosField = value;
                    this.RaisePropertyChanged("Intentos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UltimoIntento {
            get {
                return this.UltimoIntentoField;
            }
            set {
                if ((this.UltimoIntentoField.Equals(value) != true)) {
                    this.UltimoIntentoField = value;
                    this.RaisePropertyChanged("UltimoIntento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UltimoLoginExitoso {
            get {
                return this.UltimoLoginExitosoField;
            }
            set {
                if ((this.UltimoLoginExitosoField.Equals(value) != true)) {
                    this.UltimoLoginExitosoField = value;
                    this.RaisePropertyChanged("UltimoLoginExitoso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsComunicado", Namespace="http://schemas.datacontract.org/2004/07/clsEntidades")]
    [System.SerializableAttribute()]
    public partial class clsComunicado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaCreacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaFinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoNido.wcfNido.clsUsuario UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaFinal {
            get {
                return this.FechaFinalField;
            }
            set {
                if ((this.FechaFinalField.Equals(value) != true)) {
                    this.FechaFinalField = value;
                    this.RaisePropertyChanged("FechaFinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProyectoNido.wcfNido.clsUsuario Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsDistrito", Namespace="http://schemas.datacontract.org/2004/07/clsEntidades")]
    [System.SerializableAttribute()]
    public partial class clsDistrito : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbigeoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ubigeo {
            get {
                return this.UbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.UbigeoField, value) != true)) {
                    this.UbigeoField = value;
                    this.RaisePropertyChanged("Ubigeo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsNivel", Namespace="http://schemas.datacontract.org/2004/07/clsEntidades")]
    [System.SerializableAttribute()]
    public partial class clsNivel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsSalon", Namespace="http://schemas.datacontract.org/2004/07/clsEntidades")]
    [System.SerializableAttribute()]
    public partial class clsSalon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AforoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DimensionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Aforo {
            get {
                return this.AforoField;
            }
            set {
                if ((this.AforoField.Equals(value) != true)) {
                    this.AforoField = value;
                    this.RaisePropertyChanged("Aforo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dimensiones {
            get {
                return this.DimensionesField;
            }
            set {
                if ((object.ReferenceEquals(this.DimensionesField, value) != true)) {
                    this.DimensionesField = value;
                    this.RaisePropertyChanged("Dimensiones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsRol", Namespace="http://schemas.datacontract.org/2004/07/clsEntidades")]
    [System.SerializableAttribute()]
    public partial class clsRol : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreRolField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreRol {
            get {
                return this.NombreRolField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreRolField, value) != true)) {
                    this.NombreRolField = value;
                    this.RaisePropertyChanged("NombreRol");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsPermiso", Namespace="http://schemas.datacontract.org/2004/07/clsEntidades")]
    [System.SerializableAttribute()]
    public partial class clsPermiso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombrePermisoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombrePermiso {
            get {
                return this.NombrePermisoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombrePermisoField, value) != true)) {
                    this.NombrePermisoField = value;
                    this.RaisePropertyChanged("NombrePermiso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsUsuarioRol", Namespace="http://schemas.datacontract.org/2004/07/clsEntidades")]
    [System.SerializableAttribute()]
    public partial class clsUsuarioRol : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoNido.wcfNido.clsRol RolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoNido.wcfNido.clsUsuario UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProyectoNido.wcfNido.clsRol Rol {
            get {
                return this.RolField;
            }
            set {
                if ((object.ReferenceEquals(this.RolField, value) != true)) {
                    this.RolField = value;
                    this.RaisePropertyChanged("Rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProyectoNido.wcfNido.clsUsuario Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcfNido.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        ProyectoNido.wcfNido.CompositeType GetDataUsingDataContract(ProyectoNido.wcfNido.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ProyectoNido.wcfNido.CompositeType> GetDataUsingDataContractAsync(ProyectoNido.wcfNido.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidarUsuario", ReplyAction="http://tempuri.org/IService1/ValidarUsuarioResponse")]
        ProyectoNido.wcfNido.clsLogin[] ValidarUsuario(ProyectoNido.wcfNido.clsLogin login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidarUsuario", ReplyAction="http://tempuri.org/IService1/ValidarUsuarioResponse")]
        System.Threading.Tasks.Task<ProyectoNido.wcfNido.clsLogin[]> ValidarUsuarioAsync(ProyectoNido.wcfNido.clsLogin login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUsuario", ReplyAction="http://tempuri.org/IService1/GetUsuarioResponse")]
        ProyectoNido.wcfNido.clsUsuario[] GetUsuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUsuario", ReplyAction="http://tempuri.org/IService1/GetUsuarioResponse")]
        System.Threading.Tasks.Task<ProyectoNido.wcfNido.clsUsuario[]> GetUsuarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelUsuarios", ReplyAction="http://tempuri.org/IService1/DelUsuariosResponse")]
        void DelUsuarios(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelUsuarios", ReplyAction="http://tempuri.org/IService1/DelUsuariosResponse")]
        System.Threading.Tasks.Task DelUsuariosAsync(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsUsuarios", ReplyAction="http://tempuri.org/IService1/InsUsuariosResponse")]
        void InsUsuarios(ProyectoNido.wcfNido.clsUsuario Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsUsuarios", ReplyAction="http://tempuri.org/IService1/InsUsuariosResponse")]
        System.Threading.Tasks.Task InsUsuariosAsync(ProyectoNido.wcfNido.clsUsuario Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModUsuario", ReplyAction="http://tempuri.org/IService1/ModUsuarioResponse")]
        void ModUsuario(ProyectoNido.wcfNido.clsUsuario User);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModUsuario", ReplyAction="http://tempuri.org/IService1/ModUsuarioResponse")]
        System.Threading.Tasks.Task ModUsuarioAsync(ProyectoNido.wcfNido.clsUsuario User);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValClaveSegura", ReplyAction="http://tempuri.org/IService1/ValClaveSeguraResponse")]
        ProyectoNido.wcfNido.ValClaveSeguraResponse ValClaveSegura(ProyectoNido.wcfNido.ValClaveSeguraRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValClaveSegura", ReplyAction="http://tempuri.org/IService1/ValClaveSeguraResponse")]
        System.Threading.Tasks.Task<ProyectoNido.wcfNido.ValClaveSeguraResponse> ValClaveSeguraAsync(ProyectoNido.wcfNido.ValClaveSeguraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetComunicado", ReplyAction="http://tempuri.org/IService1/GetComunicadoResponse")]
        ProyectoNido.wcfNido.clsComunicado[] GetComunicado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetComunicado", ReplyAction="http://tempuri.org/IService1/GetComunicadoResponse")]
        System.Threading.Tasks.Task<ProyectoNido.wcfNido.clsComunicado[]> GetComunicadoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelComunicado", ReplyAction="http://tempuri.org/IService1/DelComunicadoResponse")]
        void DelComunicado(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelComunicado", ReplyAction="http://tempuri.org/IService1/DelComunicadoResponse")]
        System.Threading.Tasks.Task DelComunicadoAsync(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsComunicado", ReplyAction="http://tempuri.org/IService1/InsComunicadoResponse")]
        void InsComunicado(ProyectoNido.wcfNido.clsComunicado Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsComunicado", ReplyAction="http://tempuri.org/IService1/InsComunicadoResponse")]
        System.Threading.Tasks.Task InsComunicadoAsync(ProyectoNido.wcfNido.clsComunicado Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModComunicado", ReplyAction="http://tempuri.org/IService1/ModComunicadoResponse")]
        void ModComunicado(ProyectoNido.wcfNido.clsComunicado User);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModComunicado", ReplyAction="http://tempuri.org/IService1/ModComunicadoResponse")]
        System.Threading.Tasks.Task ModComunicadoAsync(ProyectoNido.wcfNido.clsComunicado User);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDistrito", ReplyAction="http://tempuri.org/IService1/GetDistritoResponse")]
        ProyectoNido.wcfNido.clsDistrito[] GetDistrito();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDistrito", ReplyAction="http://tempuri.org/IService1/GetDistritoResponse")]
        System.Threading.Tasks.Task<ProyectoNido.wcfNido.clsDistrito[]> GetDistritoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelDistrito", ReplyAction="http://tempuri.org/IService1/DelDistritoResponse")]
        void DelDistrito(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelDistrito", ReplyAction="http://tempuri.org/IService1/DelDistritoResponse")]
        System.Threading.Tasks.Task DelDistritoAsync(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsDistrito", ReplyAction="http://tempuri.org/IService1/InsDistritoResponse")]
        void InsDistrito(ProyectoNido.wcfNido.clsDistrito Distrito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsDistrito", ReplyAction="http://tempuri.org/IService1/InsDistritoResponse")]
        System.Threading.Tasks.Task InsDistritoAsync(ProyectoNido.wcfNido.clsDistrito Distrito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModDistrito", ReplyAction="http://tempuri.org/IService1/ModDistritoResponse")]
        void ModDistrito(ProyectoNido.wcfNido.clsDistrito Distrito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModDistrito", ReplyAction="http://tempuri.org/IService1/ModDistritoResponse")]
        System.Threading.Tasks.Task ModDistritoAsync(ProyectoNido.wcfNido.clsDistrito Distrito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNivel", ReplyAction="http://tempuri.org/IService1/GetNivelResponse")]
        ProyectoNido.wcfNido.clsNivel[] GetNivel();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNivel", ReplyAction="http://tempuri.org/IService1/GetNivelResponse")]
        System.Threading.Tasks.Task<ProyectoNido.wcfNido.clsNivel[]> GetNivelAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelNivel", ReplyAction="http://tempuri.org/IService1/DelNivelResponse")]
        void DelNivel(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelNivel", ReplyAction="http://tempuri.org/IService1/DelNivelResponse")]
        System.Threading.Tasks.Task DelNivelAsync(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsNivel", ReplyAction="http://tempuri.org/IService1/InsNivelResponse")]
        void InsNivel(ProyectoNido.wcfNido.clsNivel nivel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsNivel", ReplyAction="http://tempuri.org/IService1/InsNivelResponse")]
        System.Threading.Tasks.Task InsNivelAsync(ProyectoNido.wcfNido.clsNivel nivel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModNivel", ReplyAction="http://tempuri.org/IService1/ModNivelResponse")]
        void ModNivel(ProyectoNido.wcfNido.clsNivel nivel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModNivel", ReplyAction="http://tempuri.org/IService1/ModNivelResponse")]
        System.Threading.Tasks.Task ModNivelAsync(ProyectoNido.wcfNido.clsNivel nivel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSalon", ReplyAction="http://tempuri.org/IService1/GetSalonResponse")]
        ProyectoNido.wcfNido.clsSalon[] GetSalon();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSalon", ReplyAction="http://tempuri.org/IService1/GetSalonResponse")]
        System.Threading.Tasks.Task<ProyectoNido.wcfNido.clsSalon[]> GetSalonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelSalon", ReplyAction="http://tempuri.org/IService1/DelSalonResponse")]
        void DelSalon(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelSalon", ReplyAction="http://tempuri.org/IService1/DelSalonResponse")]
        System.Threading.Tasks.Task DelSalonAsync(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsSalon", ReplyAction="http://tempuri.org/IService1/InsSalonResponse")]
        void InsSalon(ProyectoNido.wcfNido.clsSalon salon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsSalon", ReplyAction="http://tempuri.org/IService1/InsSalonResponse")]
        System.Threading.Tasks.Task InsSalonAsync(ProyectoNido.wcfNido.clsSalon salon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModSalon", ReplyAction="http://tempuri.org/IService1/ModSalonResponse")]
        void ModSalon(ProyectoNido.wcfNido.clsSalon salon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModSalon", ReplyAction="http://tempuri.org/IService1/ModSalonResponse")]
        System.Threading.Tasks.Task ModSalonAsync(ProyectoNido.wcfNido.clsSalon salon);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRol", ReplyAction="http://tempuri.org/IService1/GetRolResponse")]
        ProyectoNido.wcfNido.clsRol[] GetRol();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRol", ReplyAction="http://tempuri.org/IService1/GetRolResponse")]
        System.Threading.Tasks.Task<ProyectoNido.wcfNido.clsRol[]> GetRolAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelRol", ReplyAction="http://tempuri.org/IService1/DelRolResponse")]
        void DelRol(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelRol", ReplyAction="http://tempuri.org/IService1/DelRolResponse")]
        System.Threading.Tasks.Task DelRolAsync(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsRol", ReplyAction="http://tempuri.org/IService1/InsRolResponse")]
        void InsRol(ProyectoNido.wcfNido.clsRol rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsRol", ReplyAction="http://tempuri.org/IService1/InsRolResponse")]
        System.Threading.Tasks.Task InsRolAsync(ProyectoNido.wcfNido.clsRol rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModRol", ReplyAction="http://tempuri.org/IService1/ModRolResponse")]
        void ModRol(ProyectoNido.wcfNido.clsRol rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModRol", ReplyAction="http://tempuri.org/IService1/ModRolResponse")]
        System.Threading.Tasks.Task ModRolAsync(ProyectoNido.wcfNido.clsRol rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPermiso", ReplyAction="http://tempuri.org/IService1/GetPermisoResponse")]
        ProyectoNido.wcfNido.clsPermiso[] GetPermiso();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPermiso", ReplyAction="http://tempuri.org/IService1/GetPermisoResponse")]
        System.Threading.Tasks.Task<ProyectoNido.wcfNido.clsPermiso[]> GetPermisoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelPermiso", ReplyAction="http://tempuri.org/IService1/DelPermisoResponse")]
        void DelPermiso(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelPermiso", ReplyAction="http://tempuri.org/IService1/DelPermisoResponse")]
        System.Threading.Tasks.Task DelPermisoAsync(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsPermiso", ReplyAction="http://tempuri.org/IService1/InsPermisoResponse")]
        void InsPermiso(ProyectoNido.wcfNido.clsPermiso per);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsPermiso", ReplyAction="http://tempuri.org/IService1/InsPermisoResponse")]
        System.Threading.Tasks.Task InsPermisoAsync(ProyectoNido.wcfNido.clsPermiso per);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModPermiso", ReplyAction="http://tempuri.org/IService1/ModPermisoResponse")]
        void ModPermiso(ProyectoNido.wcfNido.clsPermiso per);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModPermiso", ReplyAction="http://tempuri.org/IService1/ModPermisoResponse")]
        System.Threading.Tasks.Task ModPermisoAsync(ProyectoNido.wcfNido.clsPermiso per);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUsuarioRol", ReplyAction="http://tempuri.org/IService1/GetUsuarioRolResponse")]
        ProyectoNido.wcfNido.clsUsuarioRol[] GetUsuarioRol();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUsuarioRol", ReplyAction="http://tempuri.org/IService1/GetUsuarioRolResponse")]
        System.Threading.Tasks.Task<ProyectoNido.wcfNido.clsUsuarioRol[]> GetUsuarioRolAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelUsuarioRol", ReplyAction="http://tempuri.org/IService1/DelUsuarioRolResponse")]
        void DelUsuarioRol(int id_user, int id_rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelUsuarioRol", ReplyAction="http://tempuri.org/IService1/DelUsuarioRolResponse")]
        System.Threading.Tasks.Task DelUsuarioRolAsync(int id_user, int id_rol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsUsuarioRol", ReplyAction="http://tempuri.org/IService1/InsUsuarioRolResponse")]
        void InsUsuarioRol(ProyectoNido.wcfNido.clsUsuarioRol xUr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsUsuarioRol", ReplyAction="http://tempuri.org/IService1/InsUsuarioRolResponse")]
        System.Threading.Tasks.Task InsUsuarioRolAsync(ProyectoNido.wcfNido.clsUsuarioRol xUr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModUsuarioRol", ReplyAction="http://tempuri.org/IService1/ModUsuarioRolResponse")]
        void ModUsuarioRol(ProyectoNido.wcfNido.clsUsuarioRol xUr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ModUsuarioRol", ReplyAction="http://tempuri.org/IService1/ModUsuarioRolResponse")]
        System.Threading.Tasks.Task ModUsuarioRolAsync(ProyectoNido.wcfNido.clsUsuarioRol xUr);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValClaveSegura", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValClaveSeguraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string contrasenia;
        
        public ValClaveSeguraRequest() {
        }
        
        public ValClaveSeguraRequest(string usuario, string contrasenia) {
            this.usuario = usuario;
            this.contrasenia = contrasenia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValClaveSeguraResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValClaveSeguraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ValClaveSeguraResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public bool exito;
        
        public ValClaveSeguraResponse() {
        }
        
        public ValClaveSeguraResponse(string ValClaveSeguraResult, bool exito) {
            this.ValClaveSeguraResult = ValClaveSeguraResult;
            this.exito = exito;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ProyectoNido.wcfNido.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ProyectoNido.wcfNido.IService1>, ProyectoNido.wcfNido.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ProyectoNido.wcfNido.CompositeType GetDataUsingDataContract(ProyectoNido.wcfNido.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ProyectoNido.wcfNido.CompositeType> GetDataUsingDataContractAsync(ProyectoNido.wcfNido.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public ProyectoNido.wcfNido.clsLogin[] ValidarUsuario(ProyectoNido.wcfNido.clsLogin login) {
            return base.Channel.ValidarUsuario(login);
        }
        
        public System.Threading.Tasks.Task<ProyectoNido.wcfNido.clsLogin[]> ValidarUsuarioAsync(ProyectoNido.wcfNido.clsLogin login) {
            return base.Channel.ValidarUsuarioAsync(login);
        }
        
        public ProyectoNido.wcfNido.clsUsuario[] GetUsuario() {
            return base.Channel.GetUsuario();
        }
        
        public System.Threading.Tasks.Task<ProyectoNido.wcfNido.clsUsuario[]> GetUsuarioAsync() {
            return base.Channel.GetUsuarioAsync();
        }
        
        public void DelUsuarios(int Codigo) {
            base.Channel.DelUsuarios(Codigo);
        }
        
        public System.Threading.Tasks.Task DelUsuariosAsync(int Codigo) {
            return base.Channel.DelUsuariosAsync(Codigo);
        }
        
        public void InsUsuarios(ProyectoNido.wcfNido.clsUsuario Usuario) {
            base.Channel.InsUsuarios(Usuario);
        }
        
        public System.Threading.Tasks.Task InsUsuariosAsync(ProyectoNido.wcfNido.clsUsuario Usuario) {
            return base.Channel.InsUsuariosAsync(Usuario);
        }
        
        public void ModUsuario(ProyectoNido.wcfNido.clsUsuario User) {
            base.Channel.ModUsuario(User);
        }
        
        public System.Threading.Tasks.Task ModUsuarioAsync(ProyectoNido.wcfNido.clsUsuario User) {
            return base.Channel.ModUsuarioAsync(User);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProyectoNido.wcfNido.ValClaveSeguraResponse ProyectoNido.wcfNido.IService1.ValClaveSegura(ProyectoNido.wcfNido.ValClaveSeguraRequest request) {
            return base.Channel.ValClaveSegura(request);
        }
        
        public string ValClaveSegura(string usuario, string contrasenia, out bool exito) {
            ProyectoNido.wcfNido.ValClaveSeguraRequest inValue = new ProyectoNido.wcfNido.ValClaveSeguraRequest();
            inValue.usuario = usuario;
            inValue.contrasenia = contrasenia;
            ProyectoNido.wcfNido.ValClaveSeguraResponse retVal = ((ProyectoNido.wcfNido.IService1)(this)).ValClaveSegura(inValue);
            exito = retVal.exito;
            return retVal.ValClaveSeguraResult;
        }
        
        public System.Threading.Tasks.Task<ProyectoNido.wcfNido.ValClaveSeguraResponse> ValClaveSeguraAsync(ProyectoNido.wcfNido.ValClaveSeguraRequest request) {
            return base.Channel.ValClaveSeguraAsync(request);
        }
        
        public ProyectoNido.wcfNido.clsComunicado[] GetComunicado() {
            return base.Channel.GetComunicado();
        }
        
        public System.Threading.Tasks.Task<ProyectoNido.wcfNido.clsComunicado[]> GetComunicadoAsync() {
            return base.Channel.GetComunicadoAsync();
        }
        
        public void DelComunicado(int Codigo) {
            base.Channel.DelComunicado(Codigo);
        }
        
        public System.Threading.Tasks.Task DelComunicadoAsync(int Codigo) {
            return base.Channel.DelComunicadoAsync(Codigo);
        }
        
        public void InsComunicado(ProyectoNido.wcfNido.clsComunicado Usuario) {
            base.Channel.InsComunicado(Usuario);
        }
        
        public System.Threading.Tasks.Task InsComunicadoAsync(ProyectoNido.wcfNido.clsComunicado Usuario) {
            return base.Channel.InsComunicadoAsync(Usuario);
        }
        
        public void ModComunicado(ProyectoNido.wcfNido.clsComunicado User) {
            base.Channel.ModComunicado(User);
        }
        
        public System.Threading.Tasks.Task ModComunicadoAsync(ProyectoNido.wcfNido.clsComunicado User) {
            return base.Channel.ModComunicadoAsync(User);
        }
        
        public ProyectoNido.wcfNido.clsDistrito[] GetDistrito() {
            return base.Channel.GetDistrito();
        }
        
        public System.Threading.Tasks.Task<ProyectoNido.wcfNido.clsDistrito[]> GetDistritoAsync() {
            return base.Channel.GetDistritoAsync();
        }
        
        public void DelDistrito(int Codigo) {
            base.Channel.DelDistrito(Codigo);
        }
        
        public System.Threading.Tasks.Task DelDistritoAsync(int Codigo) {
            return base.Channel.DelDistritoAsync(Codigo);
        }
        
        public void InsDistrito(ProyectoNido.wcfNido.clsDistrito Distrito) {
            base.Channel.InsDistrito(Distrito);
        }
        
        public System.Threading.Tasks.Task InsDistritoAsync(ProyectoNido.wcfNido.clsDistrito Distrito) {
            return base.Channel.InsDistritoAsync(Distrito);
        }
        
        public void ModDistrito(ProyectoNido.wcfNido.clsDistrito Distrito) {
            base.Channel.ModDistrito(Distrito);
        }
        
        public System.Threading.Tasks.Task ModDistritoAsync(ProyectoNido.wcfNido.clsDistrito Distrito) {
            return base.Channel.ModDistritoAsync(Distrito);
        }
        
        public ProyectoNido.wcfNido.clsNivel[] GetNivel() {
            return base.Channel.GetNivel();
        }
        
        public System.Threading.Tasks.Task<ProyectoNido.wcfNido.clsNivel[]> GetNivelAsync() {
            return base.Channel.GetNivelAsync();
        }
        
        public void DelNivel(int Codigo) {
            base.Channel.DelNivel(Codigo);
        }
        
        public System.Threading.Tasks.Task DelNivelAsync(int Codigo) {
            return base.Channel.DelNivelAsync(Codigo);
        }
        
        public void InsNivel(ProyectoNido.wcfNido.clsNivel nivel) {
            base.Channel.InsNivel(nivel);
        }
        
        public System.Threading.Tasks.Task InsNivelAsync(ProyectoNido.wcfNido.clsNivel nivel) {
            return base.Channel.InsNivelAsync(nivel);
        }
        
        public void ModNivel(ProyectoNido.wcfNido.clsNivel nivel) {
            base.Channel.ModNivel(nivel);
        }
        
        public System.Threading.Tasks.Task ModNivelAsync(ProyectoNido.wcfNido.clsNivel nivel) {
            return base.Channel.ModNivelAsync(nivel);
        }
        
        public ProyectoNido.wcfNido.clsSalon[] GetSalon() {
            return base.Channel.GetSalon();
        }
        
        public System.Threading.Tasks.Task<ProyectoNido.wcfNido.clsSalon[]> GetSalonAsync() {
            return base.Channel.GetSalonAsync();
        }
        
        public void DelSalon(int Codigo) {
            base.Channel.DelSalon(Codigo);
        }
        
        public System.Threading.Tasks.Task DelSalonAsync(int Codigo) {
            return base.Channel.DelSalonAsync(Codigo);
        }
        
        public void InsSalon(ProyectoNido.wcfNido.clsSalon salon) {
            base.Channel.InsSalon(salon);
        }
        
        public System.Threading.Tasks.Task InsSalonAsync(ProyectoNido.wcfNido.clsSalon salon) {
            return base.Channel.InsSalonAsync(salon);
        }
        
        public void ModSalon(ProyectoNido.wcfNido.clsSalon salon) {
            base.Channel.ModSalon(salon);
        }
        
        public System.Threading.Tasks.Task ModSalonAsync(ProyectoNido.wcfNido.clsSalon salon) {
            return base.Channel.ModSalonAsync(salon);
        }
        
        public ProyectoNido.wcfNido.clsRol[] GetRol() {
            return base.Channel.GetRol();
        }
        
        public System.Threading.Tasks.Task<ProyectoNido.wcfNido.clsRol[]> GetRolAsync() {
            return base.Channel.GetRolAsync();
        }
        
        public void DelRol(int Codigo) {
            base.Channel.DelRol(Codigo);
        }
        
        public System.Threading.Tasks.Task DelRolAsync(int Codigo) {
            return base.Channel.DelRolAsync(Codigo);
        }
        
        public void InsRol(ProyectoNido.wcfNido.clsRol rol) {
            base.Channel.InsRol(rol);
        }
        
        public System.Threading.Tasks.Task InsRolAsync(ProyectoNido.wcfNido.clsRol rol) {
            return base.Channel.InsRolAsync(rol);
        }
        
        public void ModRol(ProyectoNido.wcfNido.clsRol rol) {
            base.Channel.ModRol(rol);
        }
        
        public System.Threading.Tasks.Task ModRolAsync(ProyectoNido.wcfNido.clsRol rol) {
            return base.Channel.ModRolAsync(rol);
        }
        
        public ProyectoNido.wcfNido.clsPermiso[] GetPermiso() {
            return base.Channel.GetPermiso();
        }
        
        public System.Threading.Tasks.Task<ProyectoNido.wcfNido.clsPermiso[]> GetPermisoAsync() {
            return base.Channel.GetPermisoAsync();
        }
        
        public void DelPermiso(int Codigo) {
            base.Channel.DelPermiso(Codigo);
        }
        
        public System.Threading.Tasks.Task DelPermisoAsync(int Codigo) {
            return base.Channel.DelPermisoAsync(Codigo);
        }
        
        public void InsPermiso(ProyectoNido.wcfNido.clsPermiso per) {
            base.Channel.InsPermiso(per);
        }
        
        public System.Threading.Tasks.Task InsPermisoAsync(ProyectoNido.wcfNido.clsPermiso per) {
            return base.Channel.InsPermisoAsync(per);
        }
        
        public void ModPermiso(ProyectoNido.wcfNido.clsPermiso per) {
            base.Channel.ModPermiso(per);
        }
        
        public System.Threading.Tasks.Task ModPermisoAsync(ProyectoNido.wcfNido.clsPermiso per) {
            return base.Channel.ModPermisoAsync(per);
        }
        
        public ProyectoNido.wcfNido.clsUsuarioRol[] GetUsuarioRol() {
            return base.Channel.GetUsuarioRol();
        }
        
        public System.Threading.Tasks.Task<ProyectoNido.wcfNido.clsUsuarioRol[]> GetUsuarioRolAsync() {
            return base.Channel.GetUsuarioRolAsync();
        }
        
        public void DelUsuarioRol(int id_user, int id_rol) {
            base.Channel.DelUsuarioRol(id_user, id_rol);
        }
        
        public System.Threading.Tasks.Task DelUsuarioRolAsync(int id_user, int id_rol) {
            return base.Channel.DelUsuarioRolAsync(id_user, id_rol);
        }
        
        public void InsUsuarioRol(ProyectoNido.wcfNido.clsUsuarioRol xUr) {
            base.Channel.InsUsuarioRol(xUr);
        }
        
        public System.Threading.Tasks.Task InsUsuarioRolAsync(ProyectoNido.wcfNido.clsUsuarioRol xUr) {
            return base.Channel.InsUsuarioRolAsync(xUr);
        }
        
        public void ModUsuarioRol(ProyectoNido.wcfNido.clsUsuarioRol xUr) {
            base.Channel.ModUsuarioRol(xUr);
        }
        
        public System.Threading.Tasks.Task ModUsuarioRolAsync(ProyectoNido.wcfNido.clsUsuarioRol xUr) {
            return base.Channel.ModUsuarioRolAsync(xUr);
        }
    }
}
